[package]
name = "mumble-sys"
version = "0.1.0"
authors = ["Zoey <Dessix@Dessix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collect_slice = "1.2.0"
parking_lot = { version = "~0.10.2", features = [ "nightly" ] }
num-traits = "0.2.11"

[build-dependencies]
bindgen = "~0.53.2"
const-concat = { git = "https://github.com/reesmanp/const-concat" }

[features]
default = []

idebuild = []
