[package]
name = "mumble-sys"
version = "0.1.0"
authors = ["Zoey <Dessix@Dessix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
collect_slice = "1.2.0"
parking_lot = { version = "~0.11", features = [ "nightly" ] }

[build-dependencies]
bindgen = "~0.55.1"
const-concat = { version = "~0.1.1", git = "https://github.com/reesmanp/const-concat", rev = "1d2339c1d89955ef7482b7d11467da3278c329ec" }
regex = "^1"

[features]
default = []

idebuild = []
